spring:
  application:
    name: distributed-order-plataform
  inventory:
    datasource:
      url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
      username: APP_INVENTORY
      password: MySecurePassword123
      driver-class-name: oracle.jdbc.OracleDriver
    liquibase:
      enabled: false
      changelog: classpath:db/changelog/inventory-node-master.yaml
      default-schema: APP_INVENTORY
      changelog-table: CHANGELOG_INVENTORY
      changelog-lock-table: CHANGELOG_LOCK_INVENTORY
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    web:
      pageable:
        serialization-mode: via_dto
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: none
    publisher-returns: false
    cache:
      channel:
        size: 25              # Expands the pool size to prevent force-closures
        checkout-timeout: 5000ms

app:
  RabbitMQ:
    order-queue: "inventory.order-created.queue"
    order-exchange: "orders.events.exchange"
    order-routing-key: "orders.created"