spring:
  application:
    name: distributed-order-plataform
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: dev_app
    password: YourPassword123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath*:db/changelog/order-node-master.yaml
  data:
    web:
      pageable:
        serialization-mode: via_dto